"""Regression tests for the locked Python dependency workflow (GitHub issue #35)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def _target_body(makefile: str, target: str) -> str:
    match = re.search(rf"(?:^|\n){re.escape(target)}:[^\n]*(?P<body>.*?)(?:\n\S|\Z)", makefile, re.DOTALL)
    assert match, f"missing Makefile target {target}"
    return match.group("body")


def test_committed_lock_has_exact_versions_hashes_and_expected_groups():
    lock = _read("requirements.lock")

    assert lock.startswith("# This file is generated by scripts/refresh-python-lock.sh")
    assert "pip-compile --all-extras" in lock
    assert "--generate-hashes" in lock
    assert "--hash=sha256:" in lock
    assert "requests==" in lock
    assert "pytest==" in lock
    assert "keyring==" in lock
    assert "pyinstaller==" in lock
    assert not re.search(r"^[a-zA-Z0-9_.-]+>=", lock, re.MULTILINE)


def test_refresh_script_keeps_pyproject_canonical_and_all_extras_locked():
    script = _read("scripts/refresh-python-lock.sh")
    requirements = _read("requirements.txt")

    assert "pyproject.toml" in script
    assert "--all-extras" in script
    assert "--allow-unsafe" in script
    assert "--generate-hashes" in script
    assert "requirements.lock" in script
    assert "pip-tools==7.6.0" in script
    assert "requirements.lock" in requirements
    assert "Deterministic installs must use requirements.lock" in requirements


def test_operator_install_and_packaging_install_from_lock_without_resolving_deps():
    install = _read("scripts/install.sh")
    package_sh = _read("scripts/package-desktop-backend.sh")
    package_ps1 = _read("scripts/package-desktop-backend.ps1")

    for text in [install, package_sh, package_ps1]:
        assert "requirements.lock" in text
        assert "--require-hashes" in text
        assert "--no-deps" in text

    assert "pip install -r requirements.txt" not in install
    assert "pip install --upgrade pyinstaller keyring" not in package_sh
    assert "pip install --upgrade pyinstaller keyring" not in package_ps1


def test_ci_installs_locked_dependencies_and_has_lock_freshness_job():
    ci = _read(".github/workflows/ci.yml")

    assert "Python dependency lock freshness" in ci
    assert "scripts/check dependency-lock" in ci
    assert "requirements.lock" in ci
    assert "cache-dependency-path:" in ci
    assert "pip install --require-hashes -r requirements.lock" in ci
    assert "pip install --no-deps -e ." in ci
    assert "pip install -r requirements.txt" not in ci
    assert "pip install -e '.[test]'" not in ci


def test_check_and_make_expose_dependency_lock_verification():
    check = _read("scripts/check")
    makefile = _read("Makefile")

    assert "dependency-lock)" in check
    assert "scripts/refresh-python-lock.sh" in check
    assert "cmp -s" in check
    assert "requirements.lock is stale" in check
    assert "dependency-lock" in re.search(r"PUBLIC_TARGETS :=(?P<body>.*?)(?:\n\n|\Z)", makefile, re.DOTALL).group("body")
    assert "scripts/check dependency-lock" in _read("docs/ci.md")
    assert "make dependency-lock" in _read("README.md")
    dependency_body = _target_body(makefile, "dependency-lock")
    assert "$(CHECK)" in dependency_body
    assert "dependency-lock" in dependency_body


def test_docs_describe_locked_operator_ci_and_desktop_handling():
    docs = _read("README.md") + "\n" + _read("docs/ci.md")

    for phrase in [
        "requirements.lock",
        "--require-hashes",
        "--no-deps",
        "canonical direct dependency declaration",
        "all optional dependency groups",
        "desktop packaging tools",
        "Playwright browser binaries",
    ]:
        assert phrase in docs
